CREATE OR REPLACE TRIGGER trig_cust_profile_change
  BEFORE
    INSERT OR
    UPDATE OR
    DELETE
  ON CUST_PROFILE
  FOR EACH ROW
BEGIN
  CASE
    WHEN INSERTING THEN
      INSERT INTO CUST_MODIFIED(TABLE_NAME, CUST_ID, SYNC, CREATE_TIME)
        VALUES('CUST_PROFILE',new.CUST_ID,'N',SYSTIMESTAMP);
    WHEN UPDATING THEN
      INSERT INTO CUST_MODIFIED(TABLE_NAME, CUST_ID, SYNC, CREATE_TIME)
        VALUES('CUST_PROFILE',new.CUST_ID,'N',SYSTIMESTAMP);
    WHEN DELETING THEN
      INSERT INTO CUST_MODIFIED(TABLE_NAME, CUST_ID, SYNC, CREATE_TIME)
        VALUES('CUST_PROFILE',old.CUST_ID,'N',SYSTIMESTAMP);
  END CASE;
END;
/